Save start page, using MiceWeb

diff --git a/save b/save
--- a/save
+++ b/save
@@ -12,10 +12,19 @@ fi
 DOMAIN="$1"
 if [[ "$2" == "" ]]
 then
-  START_URL="http://$DOMAIN"
+    START_URL="http://$DOMAIN"
 else
-  START_URL="$2"
+    START_URL="$2"
 fi
+
+type -P miceweb &>/dev/null && ISINST=1 || ISINST=0
+if [ $ISINST -eq 1 ]
+then
+    miceweb save "$START_URL"
+else
+    >&2 echo "Error: miceweb is not installed (seeing https://github.com/Robotizing/MiceWeb/)"
+fi
+
 PARAMS="--domains=$DOMAIN,www.$DOMAIN $3 $4 $5 $6 $7 $8 $9 $START_URL"
 SUBDIR="backup_$DOMAIN"
 if [ -e "$SUBDIR" ]; then
